package es.unex.sextante.gui.modeler;

import es.unex.sextante.additionalInfo.AdditionalInfo3DRasterLayer;
import es.unex.sextante.additionalInfo.AdditionalInfoBand;
import es.unex.sextante.additionalInfo.AdditionalInfoBoolean;
import es.unex.sextante.additionalInfo.AdditionalInfoFilepath;
import es.unex.sextante.additionalInfo.AdditionalInfoFixedTable;
import es.unex.sextante.additionalInfo.AdditionalInfoMultipleInput;
import es.unex.sextante.additionalInfo.AdditionalInfoNumericalValue;
import es.unex.sextante.additionalInfo.AdditionalInfoRasterLayer;
import es.unex.sextante.additionalInfo.AdditionalInfoString;
import es.unex.sextante.additionalInfo.AdditionalInfoTable;
import es.unex.sextante.additionalInfo.AdditionalInfoTableField;
import es.unex.sextante.additionalInfo.AdditionalInfoVectorLayer;
import es.unex.sextante.core.ParametersSet;
import es.unex.sextante.core.Sextante;
import es.unex.sextante.exceptions.NullParameterAdditionalInfoException;
import es.unex.sextante.exceptions.OptionalParentParameterException;
import es.unex.sextante.exceptions.RepeatedParameterNameException;
import es.unex.sextante.exceptions.UndefinedParentParameterNameException;
import es.unex.sextante.parameters.Parameter;
import es.unex.sextante.parameters.ParameterBand;
import es.unex.sextante.parameters.ParameterBoolean;
import es.unex.sextante.parameters.ParameterFixedTable;
import es.unex.sextante.parameters.ParameterMultipleInput;
import es.unex.sextante.parameters.ParameterNumericalValue;
import es.unex.sextante.parameters.ParameterPoint;
import es.unex.sextante.parameters.ParameterSelection;
import es.unex.sextante.parameters.ParameterRasterLayer;
import es.unex.sextante.parameters.Parameter3DRasterLayer;
import es.unex.sextante.parameters.ParameterString;
import es.unex.sextante.parameters.ParameterTable;
import es.unex.sextante.parameters.ParameterTableField;
import es.unex.sextante.parameters.ParameterVectorLayer;
import es.unex.sextante.parameters.ParameterFilepath;


public class ModelCodeCreator {

	public static String getJavaCode(final ModelAlgorithm alg) {

		final StringBuffer code = new StringBuffer();

		addHeader(code, alg);
		addOpening(code, alg);
		addConstants(code, alg);
		addDefineCharacteristics(code, alg);
		addProcessAlgorithm(code, alg);

		addClosing(code, alg);

		return code.toString();


	}


	private static void addConstants(final StringBuffer code,
			final ModelAlgorithm alg) {

		final ParametersSet params = alg.getParameters();
		for (int i = 0; i < params.getNumberOfParameters(); i++) {
			final Parameter param = params.getParameter(i);
			final String sName = getParameterNameFromDescription(param);
			code.append("\tpublic static final String " + sName + "=\"" + sName + "\";\n");
		}

	}


	private static void addOpening(final StringBuffer code,
			final ModelAlgorithm alg) {

		code.append("/*******************************************************/\n");
		code.append("/* This code is a stub that was auto-generated by the  */\n");
		code.append("/* gvSIG CE Modeler. There is no guarantee it will run */\n");
		code.append("/* or do anything useful in its current form.          */\n");
		code.append("/* Please review the code and amend it as required.    */\n");
		code.append("/*******************************************************/\n\n");		
		
		
		code.append("package es.unex.sextante.stubs."+alg.getGroup().replaceAll(" ", "_")+";\n\n");
		code.append("import es.unex.sextante.core.GeoAlgorithm;\n");
		code.append("import es.unex.sextante.core.AnalysisExtent;\n");
		code.append("import es.unex.sextante.core.Sextante;\n");
		code.append("import es.unex.sextante.dataObjects.IRasterLayer;\n");
		code.append("import es.unex.sextante.exceptions.GeoAlgorithmExecutionException;\n");
		code.append("import es.unex.sextante.exceptions.OptionalParentParameterException;\n");
		code.append("import es.unex.sextante.exceptions.RepeatedParameterNameException;\n");
		code.append("import es.unex.sextante.exceptions.UndefinedParentParameterNameException;\n");		
		
		code.append("\npublic class " + alg.getName().replaceAll(" ", "_") + " extends GeoAlgorithm {\n\n");

	}


	private static void addClosing(final StringBuffer code,
			final ModelAlgorithm alg) {

		code.append("}\n\n");

	}


	private static void addProcessAlgorithm(final StringBuffer code,
			final ModelAlgorithm alg) {

		code.append("\n\t@Override");
		code.append("\n\tpublic boolean processAlgorithm() {\n\n");

		String sAs = null;
		String sClass = null;
		final ParametersSet params = alg.getParameters();
		for (int i = 0; i < params.getNumberOfParameters(); i++) {
			final Parameter param = params.getParameter(i);
			if (param instanceof ParameterRasterLayer) {
				sAs = "RasterLayer";
				sClass = "IRasterLayer";
			}
			else if (param instanceof ParameterMultipleInput) {
				sAs = "ArrayList";
				sClass = "ArrayList";
			}
			else if (param instanceof Parameter3DRasterLayer) {
				sAs = "3DRasterLayer";
				sClass = "3DIRasterLayer";
			}
			else if (param instanceof ParameterTableField) {
				sAs = "Int";
				sClass = "int";
			}			
			else if (param instanceof ParameterBand) {
				sAs = "Int";
				sClass = "int";
			}
			else if (param instanceof ParameterVectorLayer) {
				sAs = "VectorLayer";
				sClass = "IVectorLayer";
			}
			else if (param instanceof ParameterTable) {
				sAs = "Table";
				sClass = "ITable";
			}
			else if (param instanceof ParameterNumericalValue) {
				sAs = "Double";
				sClass = "Double";
			}
			else if (param instanceof ParameterString) {
				sAs = "String";
				sClass = "String";

			}
			else if (param instanceof ParameterSelection) {
				sAs = "String";
				sClass = "String";

			}
			else if (param instanceof ParameterFilepath) {
				sAs = "String";
				sClass = "String";

			}
			else if (param instanceof ParameterFixedTable) {
				sAs = "Object";
				sClass = "FixedTableModel";
				final String sName = getParameterNameFromDescription(param);
				code.append("\t\t" + sClass + " " + sName.toLowerCase() + " = (FixedTableModel) m_Parameters.getParameterValueAs"
						+ sAs + "(" + sName + ");\n");
				continue;
			}
			else if (param instanceof ParameterPoint) {
				sAs = "Point";
				sClass = "Point2D";
			}
			else if (param instanceof ParameterBoolean) {
				sAs = "Boolean";
				sClass = "Boolean";
			}

			final String sName = getParameterNameFromDescription(param);
			code.append("\t\t" + sClass + " " + sName.toLowerCase() + " = m_Parameters.getParameterValueAs" + sAs + "(" + sName
					+ ");\n");


		}

		code.append("\n\t\t/**********************************/\n");
		code.append("\t\t/* Add your processing code here. */\n");
		code.append("\t\t/**********************************/\n");
		
		code.append("\n\t\treturn !m_Task.isCanceled();\n");
		code.append("\t}\n\n");


	}


	private static void addParameters(final StringBuffer code,
			final ModelAlgorithm alg) {

		final StringBuffer dependentCode = new StringBuffer();
		final ParametersSet params = alg.getParameters();
		for (int i = 0; i < params.getNumberOfParameters(); i++) {
			final Parameter param = params.getParameter(i);
			if (param instanceof ParameterRasterLayer) {
				try {
					final AdditionalInfoRasterLayer ai = (AdditionalInfoRasterLayer) param.getParameterAdditionalInfo();
					code.append("\t\t\tm_Parameters.addInputRasterLayer(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() + "\", " + new Boolean(ai.getIsMandatory()).toString() + ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {};
			}
			else if (param instanceof Parameter3DRasterLayer) {
				try {
					final AdditionalInfo3DRasterLayer ai = (AdditionalInfo3DRasterLayer) param.getParameterAdditionalInfo();
					code.append("\t\t\tm_Parameters.addInput3DRasterLayer(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() + "\", " + new Boolean(ai.getIsMandatory()).toString() + ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {};
			}
			else if (param instanceof ParameterMultipleInput) {
				try {
					final AdditionalInfoMultipleInput ai = (AdditionalInfoMultipleInput) param.getParameterAdditionalInfo();
					String sType;
					switch (ai.getDataType()) {
					case AdditionalInfoMultipleInput.DATA_TYPE_BAND:
						sType = "AdditionalInfoMultipleInput.DATA_TYPE_BAND";
						break;
					case AdditionalInfoMultipleInput.DATA_TYPE_RASTER:
						sType = "AdditionalInfoMultipleInput.DATA_TYPE_RASTER";
						break;
					case AdditionalInfoMultipleInput.DATA_TYPE_RASTER_3D:
						sType = "AdditionalInfoMultipleInput.DATA_TYPE_RASTER_3D";
						break;                     
					case AdditionalInfoMultipleInput.DATA_TYPE_TABLE:
						sType = "AdditionalInfoMultipleInput.DATA_TYPE_TABLE";
						break;
					case AdditionalInfoMultipleInput.DATA_TYPE_VECTOR_ANY:
						sType = "AdditionalInfoMultipleInput.DATA_TYPE_VECTOR_ANY";
						break;
					case AdditionalInfoMultipleInput.DATA_TYPE_VECTOR_LINE:
						sType = "AdditionalInfoMultipleInput.DATA_TYPE_VECTOR_LINE";
						break;
					case AdditionalInfoMultipleInput.DATA_TYPE_VECTOR_POINT:
						sType = "AdditionalInfoMultipleInput.DATA_TYPE_VECTOR_POINT";
						break;
					case AdditionalInfoMultipleInput.DATA_TYPE_VECTOR_POLYGON:
					default:
						sType = "AdditionalInfoMultipleInput.DATA_TYPE_VECTOR_POLYGON";
						break;
					}
					code.append("\t\t\tm_Parameters.addMultipleInput(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() + "\", " + sType + "," + new Boolean(ai.getIsMandatory()).toString()
							+ ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {};
			}
			else if (param instanceof ParameterVectorLayer) {
				try {
					final AdditionalInfoVectorLayer ai = (AdditionalInfoVectorLayer) param.getParameterAdditionalInfo();
					String sType;
					switch (ai.getShapeType()) {
					case AdditionalInfoVectorLayer.SHAPE_TYPE_ANY:
						sType = "AdditionalInfoVectorLayer.SHAPE_TYPE_ANY";
						break;
					case AdditionalInfoVectorLayer.SHAPE_TYPE_LINE:
						sType = "AdditionalInfoVectorLayer.SHAPE_TYPE_LINE";
						break;
					case AdditionalInfoVectorLayer.SHAPE_TYPE_POINT:
						sType = "AdditionalInfoVectorLayer.SHAPE_TYPE_POINT";
						break;
					case AdditionalInfoVectorLayer.SHAPE_TYPE_POLYGON:
					default:
						sType = "AdditionalInfoVectorLayer.SHAPE_TYPE_POLYGON";
						break;
					}
					code.append("\t\t\tm_Parameters.addInputVectorLayer(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() + "\", " + sType + ", "
							+ new Boolean(ai.getIsMandatory()).toString() + ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {}

			}
			else if (param instanceof ParameterTable) {
				try {
					final AdditionalInfoTable ai = (AdditionalInfoTable) param.getParameterAdditionalInfo();
					code.append("\t\t\tm_Parameters.addInputTable(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() + "\", " + new Boolean(ai.getIsMandatory()).toString() + ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {}
			}
			else if (param instanceof ParameterNumericalValue) {
				try {
					final AdditionalInfoNumericalValue ai = (AdditionalInfoNumericalValue) param.getParameterAdditionalInfo();
					String sType;
					switch (ai.getType()) {
					case AdditionalInfoNumericalValue.NUMERICAL_VALUE_INTEGER:
						sType = "AdditionalInfoNumericalValue.NUMERICAL_VALUE_INTEGER";
						break;
					default:
						sType = "AdditionalInfoNumericalValue.NUMERICAL_VALUE_DOUBLE";
					}
					code.append("\t\t\tm_Parameters.addNumericalValue(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() + "\", " + sType + ", " + Double.toString(ai.getDefaultValue())
							+ ", " + Double.toString(ai.getMinValue()) + ", " + Double.toString(ai.getMaxValue()) + ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {}
			}
			else if (param instanceof ParameterString) {
				try {
					final AdditionalInfoString ai = (AdditionalInfoString) param.getParameterAdditionalInfo();
					code.append("\t\t\tm_Parameters.addString(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() + "\", " + ai.getDefaultString().toString() + ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {}
			}
			else if (param instanceof ParameterFilepath) {
				try {
					final AdditionalInfoFilepath ai = (AdditionalInfoFilepath) param.getParameterAdditionalInfo();
					String ext;
					if ( ai.getExtensions() != null && ai.getExtensions().length > 0 
							&& ai.getExtensions()[0] != null && ai.getExtensions()[0].length() > 0 ) {
						ext = new String (ai.getExtensions()[0]);
					} else {
						ext = new String ("");
					}
					code.append("\t\t\tm_Parameters.addFilepath(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() 
							+ "\", " + new Boolean(ai.isFolder()).toString() 
							+ ", " + new Boolean(ai.isOpenDialog()).toString()
							+ ", " + new Boolean(ai.getIsVoxelData()).toString()
							+ ", \"" + ext +"\""
							+ ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {};
			}         
			else if (param instanceof ParameterFixedTable) {
				try {
					final AdditionalInfoFixedTable ai = (AdditionalInfoFixedTable) param.getParameterAdditionalInfo();
					code.append("\t\t\tm_Parameters.addFixedTable(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() + "\", " + ai.getRowsCount() + ", " + ai.getColsCount() + ", "
							+ Boolean.toString(ai.isNumberOfRowsFixed()) + ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {}
			}
			else if (param instanceof ParameterPoint) {
				code.append("\t\t\tm_Parameters.addString(" + getParameterNameFromDescription(param) + ", \""
						+ param.getParameterDescription() + "\");\n");

			}
			else if (param instanceof ParameterBoolean) {
				try {
					final AdditionalInfoBoolean ai = (AdditionalInfoBoolean) param.getParameterAdditionalInfo();
					code.append("\t\t\tm_Parameters.addBoolean(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() + "\", " + Boolean.toString(ai.getDefaultValue()) + ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {}
			}
			else if (param instanceof ParameterBand) {
				try {
					final AdditionalInfoBand ai = (AdditionalInfoBand) param.getParameterAdditionalInfo();
					dependentCode.append("\t\t\tm_Parameters.addBand(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() + "\", " + ai.getParentParameterName() + ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {}
			}
			else if (param instanceof ParameterTableField) {
				try {
					final AdditionalInfoTableField ai = (AdditionalInfoTableField) param.getParameterAdditionalInfo();
					dependentCode.append("\t\t\tm_Parameters.addTableField(" + getParameterNameFromDescription(param) + ", \""
							+ param.getParameterDescription() + "\", " + ai.getParentParameterName() + ");\n");
				}
				catch (final NullParameterAdditionalInfoException e) {}
			}

		}

		code.append(dependentCode);

	}


	private static String getParameterNameFromDescription(final Parameter param) {

		final String sDesc = param.getParameterDescription();

		return sDesc.replaceAll(" ", "_").toUpperCase();

	}


	private static void addDefineCharacteristics(final StringBuffer code,
			final ModelAlgorithm alg) {

		code.append("\n\t@Override");
		code.append("\n\tpublic void defineCharacteristics() {\n\n");

		code.append("\t\tsetName(Sextante.getText(\"" + alg.getName() + "\");\n");
		code.append("\t\tsetGroup(Sextante.getText(\"" + alg.getGroup() + "\");\n");
		code.append("\n");
		code.append("\t\ttry{\n");
		addParameters(code, alg);
		code.append("\t\t}\n");
		
		code.append("\t\tcatch (final RepeatedParameterNameException e) {\n");
		code.append("\t\t\tSextante.addErrorToLog(e);\n");
	    code.append("\t\t}\n");
	    code.append("\t\tcatch (final UndefinedParentParameterNameException e) {\n");
	    code.append("\t\t\tSextante.addErrorToLog(e);\n");
	    code.append("\t\t}\n");
	    code.append("\t\tcatch (final OptionalParentParameterException e) {\n");
	    code.append("\t\tSextante.addErrorToLog(e);\n");
	    code.append("\t\t}\n");		
		code.append("\t\tcatch(Exception e){}\n");
		code.append("\t}\n\n");

	}


	private static void addHeader(final StringBuffer code,
			final ModelAlgorithm alg) {


	}

}
