
package com.geomaticaeambiente.klemgui.ui;

import com.geomaticaeambiente.klemgui.utils.PluginUtils;
import com.vividsolutions.jump.workbench.WorkbenchContext;
import com.vividsolutions.jump.workbench.model.Layerable;
import java.awt.Point;
import java.util.List;
import java.util.UUID;
import javax.swing.JDialog;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.StyledDocument;
import org.openjump.core.rasterimage.RasterImageLayer;

/**
 *
 * @author Geomatica
 */
public class PersonalRasterCombPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonalRasterCombPanel
     * @param rasterImageLayers
     */
    public PersonalRasterCombPanel(WorkbenchContext workbenchContext,
            JDialog mainComponent) throws BadLocationException {
        this.workbenchContext = workbenchContext;
        this.mainComponent = mainComponent;
        initComponents();
        fixComponents();
        
        jTable_Rasters.setModel(dtmRasters);
        jTable_Rasters.getColumnModel().getColumn(0).setHeaderValue(PluginUtils.getResources().getString("PersonalRasterCombPanel.RasterList.label"));
//        dtmRasters.setNumRows(1);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane_RasterList = new javax.swing.JScrollPane();
        jTable_Rasters = new javax.swing.JTable();
        jPanel_Operators = new javax.swing.JPanel();
        jButton_Subtraction2 = new javax.swing.JButton();
        jButton_Multiplication2 = new javax.swing.JButton();
        jButton_Division2 = new javax.swing.JButton();
        jButton_Power2 = new javax.swing.JButton();
        jButton_Addition2 = new javax.swing.JButton();
        jButton_Modulus2 = new javax.swing.JButton();
        jButton_LessThan2 = new javax.swing.JButton();
        jButton_GreaterThan2 = new javax.swing.JButton();
        jButton_Equal2 = new javax.swing.JButton();
        jButton_NotEqual2 = new javax.swing.JButton();
        jButton_LessOrEqual2 = new javax.swing.JButton();
        jButton_MoreOrEqual2 = new javax.swing.JButton();
        jButton_BooleanNot2 = new javax.swing.JButton();
        jButton_BooleanAnd2 = new javax.swing.JButton();
        jButton_BooleanOr2 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jButton_ParOpen2 = new javax.swing.JButton();
        jButton_ParClose2 = new javax.swing.JButton();
        jPanel_Functions = new javax.swing.JPanel();
        jLabel_FunMath = new javax.swing.JLabel();
        jComboBox_FunMath = new javax.swing.JComboBox();
        jLabel_FunTrig = new javax.swing.JLabel();
        jComboBox_FunTrig = new javax.swing.JComboBox();
        jScrollPane_Expression = new javax.swing.JScrollPane();
        jTextArea_Expr = new javax.swing.JTextArea();
        jToggleButton_Help = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(405, 365));
        setMinimumSize(new java.awt.Dimension(405, 365));
        setPreferredSize(new java.awt.Dimension(405, 365));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        jScrollPane_RasterList.setMaximumSize(new java.awt.Dimension(50, 50));
        jScrollPane_RasterList.setMinimumSize(new java.awt.Dimension(200, 100));

        jTable_Rasters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Rasters.setMaximumSize(new java.awt.Dimension(160, 230));
        jTable_Rasters.setMinimumSize(new java.awt.Dimension(160, 230));
        jTable_Rasters.setPreferredSize(new java.awt.Dimension(160, 230));
        jTable_Rasters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_RastersMouseClicked(evt);
            }
        });
        jScrollPane_RasterList.setViewportView(jTable_Rasters);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(jScrollPane_RasterList, gridBagConstraints);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/geomaticaeambiente/klemgui/resources/Bundle"); // NOI18N
        jPanel_Operators.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("PersonalRasterCombPanel.jPanel_Operators.border.title"))); // NOI18N
        jPanel_Operators.setMaximumSize(new java.awt.Dimension(225, 150));
        jPanel_Operators.setMinimumSize(new java.awt.Dimension(225, 150));
        jPanel_Operators.setPreferredSize(new java.awt.Dimension(225, 150));
        jPanel_Operators.setLayout(new java.awt.GridBagLayout());

        jButton_Subtraction2.setText(bundle.getString("PersonalRasterCombPanel.jButton_Subtraction2.text")); // NOI18N
        jButton_Subtraction2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_Subtraction2.toolTipText")); // NOI18N
        jButton_Subtraction2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_Subtraction2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_Subtraction2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_Subtraction2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_Subtraction2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Subtraction2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 0, 0);
        jPanel_Operators.add(jButton_Subtraction2, gridBagConstraints);

        jButton_Multiplication2.setText(bundle.getString("PersonalRasterCombPanel.jButton_Multiplication2.text")); // NOI18N
        jButton_Multiplication2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_Multiplication2.toolTipText")); // NOI18N
        jButton_Multiplication2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_Multiplication2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_Multiplication2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_Multiplication2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_Multiplication2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Multiplication2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 0, 0);
        jPanel_Operators.add(jButton_Multiplication2, gridBagConstraints);

        jButton_Division2.setText(bundle.getString("PersonalRasterCombPanel.jButton_Division2.text")); // NOI18N
        jButton_Division2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_Division2.toolTipText")); // NOI18N
        jButton_Division2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_Division2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_Division2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_Division2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_Division2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Division2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 0, 0);
        jPanel_Operators.add(jButton_Division2, gridBagConstraints);

        jButton_Power2.setText(bundle.getString("PersonalRasterCombPanel.jButton_Power2.text")); // NOI18N
        jButton_Power2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_Power2.toolTipText")); // NOI18N
        jButton_Power2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_Power2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_Power2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_Power2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_Power2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Power2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 0, 0);
        jPanel_Operators.add(jButton_Power2, gridBagConstraints);

        jButton_Addition2.setText(bundle.getString("PersonalRasterCombPanel.jButton_Addition2.text")); // NOI18N
        jButton_Addition2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_Addition2.toolTipText")); // NOI18N
        jButton_Addition2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_Addition2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_Addition2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_Addition2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_Addition2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Addition2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 12, 0, 0);
        jPanel_Operators.add(jButton_Addition2, gridBagConstraints);

        jButton_Modulus2.setText(bundle.getString("PersonalRasterCombPanel.jButton_Modulus2.text")); // NOI18N
        jButton_Modulus2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_Modulus2.toolTipText")); // NOI18N
        jButton_Modulus2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_Modulus2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_Modulus2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_Modulus2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_Modulus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Modulus2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 0, 0);
        jPanel_Operators.add(jButton_Modulus2, gridBagConstraints);

        jButton_LessThan2.setText(bundle.getString("PersonalRasterCombPanel.jButton_LessThan2.text")); // NOI18N
        jButton_LessThan2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_LessThan2.toolTipText")); // NOI18N
        jButton_LessThan2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_LessThan2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_LessThan2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_LessThan2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_LessThan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LessThan2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        jPanel_Operators.add(jButton_LessThan2, gridBagConstraints);

        jButton_GreaterThan2.setText(bundle.getString("PersonalRasterCombPanel.jButton_GreaterThan2.text")); // NOI18N
        jButton_GreaterThan2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_GreaterThan2.toolTipText")); // NOI18N
        jButton_GreaterThan2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_GreaterThan2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_GreaterThan2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_GreaterThan2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_GreaterThan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GreaterThan2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel_Operators.add(jButton_GreaterThan2, gridBagConstraints);

        jButton_Equal2.setText(bundle.getString("PersonalRasterCombPanel.jButton_Equal2.text")); // NOI18N
        jButton_Equal2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_Equal2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_Equal2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_Equal2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_Equal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Equal2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel_Operators.add(jButton_Equal2, gridBagConstraints);

        jButton_NotEqual2.setText(bundle.getString("PersonalRasterCombPanel.jButton_NotEqual2.text")); // NOI18N
        jButton_NotEqual2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_NotEqual2.toolTipText")); // NOI18N
        jButton_NotEqual2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_NotEqual2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_NotEqual2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_NotEqual2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_NotEqual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NotEqual2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel_Operators.add(jButton_NotEqual2, gridBagConstraints);

        jButton_LessOrEqual2.setText(bundle.getString("PersonalRasterCombPanel.jButton_LessOrEqual2.text")); // NOI18N
        jButton_LessOrEqual2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_LessOrEqual2.toolTipText")); // NOI18N
        jButton_LessOrEqual2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_LessOrEqual2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_LessOrEqual2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_LessOrEqual2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_LessOrEqual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LessOrEqual2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel_Operators.add(jButton_LessOrEqual2, gridBagConstraints);

        jButton_MoreOrEqual2.setText(bundle.getString("PersonalRasterCombPanel.jButton_MoreOrEqual2.text")); // NOI18N
        jButton_MoreOrEqual2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_MoreOrEqual2.toolTipText")); // NOI18N
        jButton_MoreOrEqual2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_MoreOrEqual2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_MoreOrEqual2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_MoreOrEqual2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_MoreOrEqual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MoreOrEqual2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel_Operators.add(jButton_MoreOrEqual2, gridBagConstraints);

        jButton_BooleanNot2.setText(bundle.getString("PersonalRasterCombPanel.jButton_BooleanNot2.text")); // NOI18N
        jButton_BooleanNot2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_BooleanNot2.toolTipText")); // NOI18N
        jButton_BooleanNot2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_BooleanNot2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_BooleanNot2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_BooleanNot2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_BooleanNot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BooleanNot2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 19, 0);
        jPanel_Operators.add(jButton_BooleanNot2, gridBagConstraints);

        jButton_BooleanAnd2.setText(bundle.getString("PersonalRasterCombPanel.jButton_BooleanAnd2.text")); // NOI18N
        jButton_BooleanAnd2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_BooleanAnd2.toolTipText")); // NOI18N
        jButton_BooleanAnd2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_BooleanAnd2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_BooleanAnd2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_BooleanAnd2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_BooleanAnd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BooleanAnd2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 19, 0);
        jPanel_Operators.add(jButton_BooleanAnd2, gridBagConstraints);

        jButton_BooleanOr2.setText(bundle.getString("PersonalRasterCombPanel.jButton_BooleanOr2.text")); // NOI18N
        jButton_BooleanOr2.setToolTipText(bundle.getString("PersonalRasterCombPanel.jButton_BooleanOr2.toolTipText")); // NOI18N
        jButton_BooleanOr2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_BooleanOr2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_BooleanOr2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_BooleanOr2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_BooleanOr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BooleanOr2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 19, 0);
        jPanel_Operators.add(jButton_BooleanOr2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 198;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 0, 6);
        jPanel_Operators.add(jSeparator6, gridBagConstraints);

        jButton_ParOpen2.setText(bundle.getString("PersonalRasterCombPanel.jButton_ParOpen2.text")); // NOI18N
        jButton_ParOpen2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_ParOpen2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_ParOpen2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_ParOpen2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_ParOpen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ParOpen2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 19, 0);
        jPanel_Operators.add(jButton_ParOpen2, gridBagConstraints);

        jButton_ParClose2.setText(bundle.getString("PersonalRasterCombPanel.jButton_ParClose2.text")); // NOI18N
        jButton_ParClose2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_ParClose2.setMaximumSize(new java.awt.Dimension(29, 29));
        jButton_ParClose2.setMinimumSize(new java.awt.Dimension(29, 29));
        jButton_ParClose2.setPreferredSize(new java.awt.Dimension(29, 29));
        jButton_ParClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ParClose2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 19, 0);
        jPanel_Operators.add(jButton_ParClose2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 8);
        add(jPanel_Operators, gridBagConstraints);

        jPanel_Functions.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("PersonalRasterCombPanel.jPanel_Functions.border.title"))); // NOI18N
        jPanel_Functions.setMaximumSize(new java.awt.Dimension(225, 85));
        jPanel_Functions.setMinimumSize(new java.awt.Dimension(225, 85));
        jPanel_Functions.setPreferredSize(new java.awt.Dimension(225, 85));
        jPanel_Functions.setLayout(new java.awt.GridBagLayout());

        jLabel_FunMath.setText(bundle.getString("PersonalRasterCombPanel.jLabel_FunMath.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        jPanel_Functions.add(jLabel_FunMath, gridBagConstraints);

        jComboBox_FunMath.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_FunMath.setMaximumSize(new java.awt.Dimension(95, 20));
        jComboBox_FunMath.setMinimumSize(new java.awt.Dimension(95, 20));
        jComboBox_FunMath.setPreferredSize(new java.awt.Dimension(95, 20));
        jComboBox_FunMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_FunMathActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel_Functions.add(jComboBox_FunMath, gridBagConstraints);

        jLabel_FunTrig.setText(bundle.getString("PersonalRasterCombPanel.jLabel_FunTrig.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        jPanel_Functions.add(jLabel_FunTrig, gridBagConstraints);

        jComboBox_FunTrig.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_FunTrig.setMaximumSize(new java.awt.Dimension(95, 20));
        jComboBox_FunTrig.setMinimumSize(new java.awt.Dimension(95, 20));
        jComboBox_FunTrig.setPreferredSize(new java.awt.Dimension(95, 20));
        jComboBox_FunTrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_FunTrigActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel_Functions.add(jComboBox_FunTrig, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(jPanel_Functions, gridBagConstraints);

        jTextArea_Expr.setColumns(20);
        jTextArea_Expr.setRows(3);
        jTextArea_Expr.setMaximumSize(new java.awt.Dimension(350, 70));
        jTextArea_Expr.setMinimumSize(new java.awt.Dimension(350, 70));
        jTextArea_Expr.setPreferredSize(new java.awt.Dimension(350, 70));
        jScrollPane_Expression.setViewportView(jTextArea_Expr);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        add(jScrollPane_Expression, gridBagConstraints);

        jToggleButton_Help.setText(bundle.getString("PersonalRasterCombPanel.jToggleButton_Help.text")); // NOI18N
        jToggleButton_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_HelpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        add(jToggleButton_Help, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_RastersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_RastersMouseClicked

        int row = jTable_Rasters.rowAtPoint(new Point(evt.getX(), evt.getY()));
        int col = jTable_Rasters.columnAtPoint(new Point(evt.getX(), evt.getY()));

        addStringToTextArea(dtmRasters.getValueAt(row, col).toString());
    }//GEN-LAST:event_jTable_RastersMouseClicked

    private void jButton_Subtraction2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Subtraction2ActionPerformed

        addStringToTextArea("-");
    }//GEN-LAST:event_jButton_Subtraction2ActionPerformed

    private void jButton_Multiplication2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Multiplication2ActionPerformed

        addStringToTextArea("*");
    }//GEN-LAST:event_jButton_Multiplication2ActionPerformed

    private void jButton_Division2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Division2ActionPerformed

        addStringToTextArea("/");
    }//GEN-LAST:event_jButton_Division2ActionPerformed

    private void jButton_Power2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Power2ActionPerformed

        addStringToTextArea("^");
    }//GEN-LAST:event_jButton_Power2ActionPerformed

    private void jButton_Addition2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Addition2ActionPerformed

        addStringToTextArea("+");
    }//GEN-LAST:event_jButton_Addition2ActionPerformed

    private void jButton_Modulus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Modulus2ActionPerformed

        addStringToTextArea("%");
    }//GEN-LAST:event_jButton_Modulus2ActionPerformed

    private void jButton_LessThan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LessThan2ActionPerformed

        addStringToTextArea("<");
    }//GEN-LAST:event_jButton_LessThan2ActionPerformed

    private void jButton_GreaterThan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GreaterThan2ActionPerformed

        addStringToTextArea(">");
    }//GEN-LAST:event_jButton_GreaterThan2ActionPerformed

    private void jButton_Equal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Equal2ActionPerformed

        addStringToTextArea("==");
    }//GEN-LAST:event_jButton_Equal2ActionPerformed

    private void jButton_NotEqual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NotEqual2ActionPerformed

        addStringToTextArea("!=");
    }//GEN-LAST:event_jButton_NotEqual2ActionPerformed

    private void jButton_LessOrEqual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LessOrEqual2ActionPerformed

        addStringToTextArea("<=");
    }//GEN-LAST:event_jButton_LessOrEqual2ActionPerformed

    private void jButton_MoreOrEqual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MoreOrEqual2ActionPerformed

        addStringToTextArea(">=");
    }//GEN-LAST:event_jButton_MoreOrEqual2ActionPerformed

    private void jButton_BooleanNot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BooleanNot2ActionPerformed

        addStringToTextArea("!");
    }//GEN-LAST:event_jButton_BooleanNot2ActionPerformed

    private void jButton_BooleanAnd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BooleanAnd2ActionPerformed

        addStringToTextArea("&&");
    }//GEN-LAST:event_jButton_BooleanAnd2ActionPerformed

    private void jButton_BooleanOr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BooleanOr2ActionPerformed

        addStringToTextArea("||");
    }//GEN-LAST:event_jButton_BooleanOr2ActionPerformed

    private void jButton_ParOpen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ParOpen2ActionPerformed

        addStringToTextArea("(");
    }//GEN-LAST:event_jButton_ParOpen2ActionPerformed

    private void jButton_ParClose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ParClose2ActionPerformed

        addStringToTextArea(")");
    }//GEN-LAST:event_jButton_ParClose2ActionPerformed

    private void jComboBox_FunMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_FunMathActionPerformed

        if(updateCombos){
            addStringToTextArea(jComboBox_FunMath.getSelectedItem().toString());
            jComboBox_FunMath.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jComboBox_FunMathActionPerformed

    private void jComboBox_FunTrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_FunTrigActionPerformed

        if(updateCombos){
            addStringToTextArea(jComboBox_FunTrig.getSelectedItem().toString());
            jComboBox_FunTrig.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jComboBox_FunTrigActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
              
        
    }//GEN-LAST:event_formComponentShown

    private void jToggleButton_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_HelpActionPerformed
        
        
        if(jToggleButton_Help.isSelected()){
            
            jDialog_Help.setLocationRelativeTo(this);
            jDialog_Help.setVisible(true);
        } else {

            jDialog_Help.setVisible(false);
        }
        
    }//GEN-LAST:event_jToggleButton_HelpActionPerformed

    private void fixComponents() throws BadLocationException{
         updateCombos = false;      
        
        this.addAncestorListener(new AncestorListener() {

             @Override
             public void ancestorAdded(AncestorEvent event) {
                 
                 updateRasterList();
                 
             }

             @Override
             public void ancestorRemoved(AncestorEvent event) {
                 
             }

             @Override
             public void ancestorMoved(AncestorEvent event) {
                 
             }
             
         });
        
        // Fill up combo boxes
        String[] funcsMath = new String[5];
        funcsMath[0] = "abs()";
        funcsMath[1] = "exp()";
        funcsMath[2] = "ln()";
        funcsMath[3] = "log()";
        funcsMath[4] = "sqrt()";

        String[] funcsTrig = new String[12];
        funcsTrig[0] = "sin()";
        funcsTrig[1] = "cos()";
        funcsTrig[2] = "tan()";
        funcsTrig[3] = "asin()";
        funcsTrig[4] = "acos()";
        funcsTrig[5] = "atan()";
        funcsTrig[6] = "sinh()";
        funcsTrig[7] = "cosh()";
        funcsTrig[8] = "tanh()";
        funcsTrig[9] = "asinh()";
        funcsTrig[10] = "acosh()";
        funcsTrig[11] = "atanh()";     
        
               
        jComboBox_FunMath.removeAllItems();
        jComboBox_FunMath.addItem(makeObj(""));
        for (String funcsMath1 : funcsMath) {
            jComboBox_FunMath.addItem(makeObj(funcsMath1));
        }

        jComboBox_FunTrig.removeAllItems();
        jComboBox_FunTrig.addItem(makeObj(""));
        for (String funcsTrig1 : funcsTrig) {
            jComboBox_FunTrig.addItem(makeObj(funcsTrig1));
        }
        
        updateCombos = true;     
        jDialog_Help = new HelpDialog(mainComponent, false);
        jDialog_Help.initComponents(getPrjFileHelpDoc());
        
    }
    
    public void updateRasterList() {
        
        List<RasterImageLayer> layerables = workbenchContext.getLayerManager().getLayerables(RasterImageLayer.class);
        // Clean table
        for(int r=0; r<dtmRasters.getRowCount(); r++){
            dtmRasters.setValueAt(null, r, 0);
        }

        rasCount = layerables.size();
        rasList = new String[rasCount][2];
        dtmRasters.setRowCount(rasCount);

        rasSel = new boolean[rasCount];

        // Fill up table and raster array
        for(int n=0; n<layerables.size(); n++){
            rasList[n][0] = layerables.get(n).getName();
            rasList[n][1] = layerables.get(n).getImageFileName();

            dtmRasters.setValueAt(layerables.get(n).getName(),n, 0);
            rasSel[n] = false;
        }
        
    }
    
    private Object makeObj(final String item)  {
        return new Object() {@Override
        public String toString() { return item; } };
    }
    
    private void addStringToTextArea(String textToAdd){

        String textBefore = jTextArea_Expr.getText();
        String textAfter;
        int caretPosition = jTextArea_Expr.getCaretPosition();
        if(jTextArea_Expr.getSelectedText()==null){
            textAfter = textBefore.substring(0, caretPosition) + textToAdd + textBefore.substring(caretPosition, textBefore.length());
            jTextArea_Expr.setText(textAfter);
            jTextArea_Expr.setCaretPosition(caretPosition + textToAdd.length());
        }else{
            int selStart = jTextArea_Expr.getSelectionStart();
            int selEnd = jTextArea_Expr.getSelectionEnd();
            textAfter = textBefore.substring(0, selStart) + textToAdd + textBefore.substring(selEnd, textBefore.length());        
            jTextArea_Expr.setText(textAfter);
            jTextArea_Expr.setCaretPosition(selStart + textToAdd.length());
        }
        jTextArea_Expr.requestFocus();
        
    }
    
    // Create table model for files and set it to non editable
    private final DefaultTableModel dtmRasters = new DefaultTableModel(1,1){

        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    
    
    public boolean[] getSelRaster(){
        
        // Find variables in expression
        for(int i=0; i<rasCount; i++){
            if(jTextArea_Expr.getText().lastIndexOf(rasList[i][0]) >= 0){
                rasSel[i] = true;
            }else{
                rasSel[i] = false;
            }
        }
        
        return rasSel;
    }
    
    public UUID[] getSelRastersUUIds() {
        
        UUID[] uuids = new UUID[rasCount];
        List<RasterImageLayer> layerables = workbenchContext.getLayerManager().getLayerables(RasterImageLayer.class);
        for(int i=0; i<rasCount; i++){
            if(jTextArea_Expr.getText().lastIndexOf(rasList[i][0]) >= 0){
                uuids[i] = layerables.get(i).getUUID();
            }else{
                uuids[i] = null;
            }
        }
        
        return uuids;        

    }
    
    public String getExpression(){        
        return jTextArea_Expr.getText();
    }
    
    private StyledDocument getPrjFileHelpDoc() throws BadLocationException{       
            
        StyledDocument style = new DefaultStyledDocument();
        style.insertString(style.getLength(), PluginUtils.getResources().getString("RasterComboPlugIn.How1.text").concat(newLine), null);
        style.insertString(style.getLength(), PluginUtils.getResources().getString("RasterComboPlugIn.How2.text").concat(newLine), null);
        style.insertString(style.getLength(), PluginUtils.getResources().getString("RasterComboPlugIn.How3.text").concat(newLine), null);
        style.insertString(style.getLength(), PluginUtils.getResources().getString("RasterComboPlugIn.How4.text").concat(newLine), null);
        style.insertString(style.getLength(), PluginUtils.getResources().getString("RasterComboPlugIn.How5.text").concat(newLine), null);
        style.insertString(style.getLength(), PluginUtils.getResources().getString("RasterComboPlugIn.How6.text").concat(newLine), null);
        style.insertString(style.getLength(), PluginUtils.getResources().getString("RasterComboPlugIn.How7.text").concat(newLine), null);
        style.insertString(style.getLength(), PluginUtils.getResources().getString("RasterComboPlugIn.How8.text").concat(newLine), null);
        style.insertString(style.getLength(), PluginUtils.getResources().getString("RasterComboPlugIn.How9.text").concat(newLine), null);
        style.insertString(style.getLength(), PluginUtils.getResources().getString("RasterComboPlugIn.How10.text").concat(newLine), null);
        return style;
            
    }
        
         
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Addition2;
    private javax.swing.JButton jButton_BooleanAnd2;
    private javax.swing.JButton jButton_BooleanNot2;
    private javax.swing.JButton jButton_BooleanOr2;
    private javax.swing.JButton jButton_Division2;
    private javax.swing.JButton jButton_Equal2;
    private javax.swing.JButton jButton_GreaterThan2;
    private javax.swing.JButton jButton_LessOrEqual2;
    private javax.swing.JButton jButton_LessThan2;
    private javax.swing.JButton jButton_Modulus2;
    private javax.swing.JButton jButton_MoreOrEqual2;
    private javax.swing.JButton jButton_Multiplication2;
    private javax.swing.JButton jButton_NotEqual2;
    private javax.swing.JButton jButton_ParClose2;
    private javax.swing.JButton jButton_ParOpen2;
    private javax.swing.JButton jButton_Power2;
    private javax.swing.JButton jButton_Subtraction2;
    private javax.swing.JComboBox jComboBox_FunMath;
    private javax.swing.JComboBox jComboBox_FunTrig;
    private javax.swing.JLabel jLabel_FunMath;
    private javax.swing.JLabel jLabel_FunTrig;
    private javax.swing.JPanel jPanel_Functions;
    private javax.swing.JPanel jPanel_Operators;
    private javax.swing.JScrollPane jScrollPane_Expression;
    private javax.swing.JScrollPane jScrollPane_RasterList;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable_Rasters;
    private javax.swing.JTextArea jTextArea_Expr;
    private javax.swing.JToggleButton jToggleButton_Help;
    // End of variables declaration//GEN-END:variables

    private final WorkbenchContext workbenchContext;
    private boolean updateCombos = false;
    private boolean[] rasSel = null;
    private int rasCount = 0;
    private String[][] rasList = null;
    private final JDialog mainComponent;
    private HelpDialog jDialog_Help;
    private final String newLine = "\n";
    
    
//    class HelpDialog extends JDialog{
//
//        public HelpDialog(java.awt.Frame parent, boolean modal) throws BadLocationException {
//            super(parent, modal);
//            initComponents();
//        }
//        
//        private void initComponents() throws BadLocationException{
//            
//            setTitle(PluginUtils.getResources().getString("PersonalRasterCombPanel.jToggleButton_Help.text"));
//            
//            GridBagConstraints gridBagConstraints = new GridBagConstraints();
//            JPanel jPanel_Help = new JPanel();
//            jPanel_Help.setLayout(new GridBagLayout());
//            
//            JScrollPane jScrollPane_Help = new JScrollPane();
//            JTextPane jTextPane_Help = new JTextPane();
//            jTextPane_Help.setEditable(false);
//            jTextPane_Help.setStyledDocument(getPrjFileHelpDoc());
//
//            jScrollPane_Help.setViewportView(jTextPane_Help);
//            
//            gridBagConstraints = new java.awt.GridBagConstraints();
//            gridBagConstraints.gridx = 0;
//            gridBagConstraints.gridy = 0;
//            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
//            gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
//            gridBagConstraints.weightx = 1.0;
//            gridBagConstraints.weighty = 1.0;
//            gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
//            jPanel_Help.add(jScrollPane_Help, gridBagConstraints);
//            
//            gridBagConstraints = new java.awt.GridBagConstraints();
//            gridBagConstraints.gridx = 0;
//            gridBagConstraints.gridy = 0;
//            gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
//            gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 10);
//            this.add(jPanel_Help);
//            
////            jTextArea1.setText("Trallalero trallal'");            
//
//            this.setType(java.awt.Window.Type.UTILITY);
//            this.setUndecorated(false);
//            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
//            pack();
//        }
//        
//        
        
        
    
    
    
    
    
    
}
