package com.geomaticaeambiente.klemgui.ui;

import com.geomaticaeambiente.klemgui.utils.PersonalChart;
import com.geomaticaeambiente.klemgui.utils.PersonalChartHydrograph;
import com.geomaticaeambiente.klemgui.utils.PersonalChartHyetograph;
import com.geomaticaeambiente.klemgui.utils.PersonalChartKlem;
import java.awt.GridBagConstraints;
import javax.swing.BorderFactory;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author Geomatica
 */
public class PersonalChartPanelComponent extends javax.swing.JPanel {

    /**
     * Creates new form ChartPanelComponent
     * @param personalChart
     */
    public PersonalChartPanelComponent(PersonalChart personalChart) {
        
        this.personalChart = personalChart;
                
        initComponents();
        fixComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void fixComponents() {
        
        removeAll();
        
        ChartPanel chartPanel = null;
        if(personalChart.getType() == PersonalChart.Type.HYETOGRAPH){
            PersonalChartHyetograph personalhyeto = (PersonalChartHyetograph) personalChart;
            chartPanel = personalhyeto.buildGraph();
        } else if(personalChart.getType() == PersonalChart.Type.HYDROGRAPH){
            PersonalChartHydrograph personalhydro = (PersonalChartHydrograph) personalChart;
            chartPanel = personalhydro.buildGraph();  
        } else if(personalChart.getType() == PersonalChart.Type.KLEM){
            PersonalChartKlem personalhydro = (PersonalChartKlem) personalChart;
            chartPanel = personalhydro.buildGraph();  
        }
        
        GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 0); //space belove a component
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        chartPanel.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        
        add(chartPanel, gridBagConstraints);
        
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public PersonalChart getPersonalChart() {
        return personalChart;
    }
    
    private final PersonalChart personalChart;
   
    
}
