package com.geomaticaeambiente.klemgui.ui;

import java.awt.GridBagConstraints;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author Geomatica
 */
public class RadioButtonsPanel extends javax.swing.JPanel {

    /**
     * Creates new form RadioButtonsPanel
     * @param labels
     */
    public RadioButtonsPanel(String... labels) {
        this.labels = labels;
        initComponents();
        fixComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void fixComponents(){
        
//        setBorder(new TitledBorder(""));
       
        int high = 0; 
        int maxWidth = 0;
        int el_numbers = labels.length;
        jradioButtons = new JRadioButton[el_numbers];
        ButtonGroup buttonGroup = new ButtonGroup();
        GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        
        for(int n=0; n<el_numbers; n++){
            
            jradioButtons[n] = new JRadioButton(labels[n]);
            
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = n;
            gridBagConstraints.weightx = 1;
            gridBagConstraints.weighty = 1;
            gridBagConstraints.insets = new java.awt.Insets(0,0,0,0); //space belove a component
            gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;

            add(jradioButtons[n], gridBagConstraints);
            buttonGroup.add(jradioButtons[n]);
        }
        
        jradioButtons[0].setSelected(true);
        

        
    }

    public int getSelectedIndex(){
        for(int n=0; n< jradioButtons.length; n++){
            if(jradioButtons[n].isSelected() == true) {
                return n;
            }            
        }
        return -1;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private String[] labels;
    private JRadioButton[] jradioButtons;
    


}
